name: '📚 Documentation'
description: A request to update or improve euphony-hub-collector documentation
title: "[Documentation] <title>"
labels: "documentation"

body:
  - type: textarea
    attributes:
      label: What is the improvement or update you wish to see?
      description: 'Ex. I want more detailed explanation of project setup.'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Is there any context that might help us understand?
      description: A clear description of any added context that might help us understand.
    validations:
      required: true
  - type: input
    attributes:
      label: Does the docs page already exist? Please link to it.
      description: 'Ex. https://github.com/yeonns/git-practice/README.md'
    validations:
      required: false