name: "💡 Feature Request"
description: Request an idea for this project
title: "[Request] <title>"
labels: "feature proposal"
body:
  - type: checkboxes
    attributes:
      label: Does the feature exist in the most recent commit?
      options:
        - label: It doesn't exist.
  - type: textarea
    attributes:
      label: Describe the proposal
      description: A clear and concise description of what you want to happen.
      placeholder : |
        Ex. I want the solution like [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why do we need this feature?
      description: A clear and concise description of what the problem is.   
      placeholder : | 
        Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder : |
        Ex. I want to extend the function A by adding someting more
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: Add any other context or screenshots about the feature request here.
      placeholder : | 
        context, screenshots, related links , etc.
    validations:
      required: false
 